### ISSUE TITLE
绝大部分服务无法正常使用

### ISSUE THREAD

**Issue by Butter934** [FudanSELab/train-ticket#117]
使用docker-compose构建此项目，访问8080端口只验证码服务可以使用，其他服务都调用不了，查看其他服务的log，几乎都抛出了与mongodb相关的异常:
```
 2020-07-20 06:17:09.719  INFO 1 --- [nce-mongo:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server ts-assurance-mongo:27017

com.mongodb.MongoSocketException: ts-assurance-mongo
        at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:188) ~[mongodb-driver-core-3.4.3.jar!/:na]
        at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:57) ~[mongodb-driver-core-3.4.3.jar!/:na]
        at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[mongodb-driver-core-3.4.3.jar!/:na]
        at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115) ~[mongodb-driver-core-3.4.3.jar!/:na]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:113) ~[mongodb-driver-core-3.4.3.jar!/:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: java.net.UnknownHostException: ts-assurance-mongo
        at java.net.InetAddress.getAllByName0(InetAddress.java:1280) ~[na:1.8.0_111]
        at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[na:1.8.0_111]
        at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[na:1.8.0_111]
        at java.net.InetAddress.getByName(InetAddress.java:1076) ~[na:1.8.0_111]
        at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:186) ~[mongodb-driver-core-3.4.3.jar!/:na]
        ... 5 common frames omitted
```

以下是对应mongodb container的log
```
2020-07-19T07:35:48.693+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
2020-07-19T07:35:48.960+0000 W  ASIO     [main] No TransportLayer configured during NetworkInterface startup
2020-07-19T07:35:49.022+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=678fbb082c9b
2020-07-19T07:35:49.034+0000 I  CONTROL  [initandlisten] db version v4.2.8
2020-07-19T07:35:49.035+0000 I  CONTROL  [initandlisten] git version: 43d25964249164d76d5e04dd6cf38f6111e21f5f
2020-07-19T07:35:49.035+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
2020-07-19T07:35:49.037+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
2020-07-19T07:35:49.038+0000 I  CONTROL  [initandlisten] modules: none
2020-07-19T07:35:49.038+0000 I  CONTROL  [initandlisten] build environment:
2020-07-19T07:35:49.038+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
2020-07-19T07:35:49.039+0000 I  CONTROL  [initandlisten]     distarch: x86_64
2020-07-19T07:35:49.039+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
2020-07-19T07:35:49.039+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "*" } }
2020-07-19T07:35:49.054+0000 I  STORAGE  [initandlisten]
2020-07-19T07:35:49.082+0000 I  STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2020-07-19T07:35:49.087+0000 I  STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2020-07-19T07:35:49.099+0000 I  STORAGE  [initandlisten] error creating journal dir /data/db/journal boost::filesystem::create_directory: No space left on device: "/data/db/journal"
2020-07-19T07:35:49.108+0000 I  STORAGE  [initandlisten] exception in initAndListen std::exception: boost::filesystem::create_directory: No space left on device: "/data/db/journal", terminating
2020-07-19T07:35:49.118+0000 I  NETWORK  [initandlisten] shutdown: going to close listening sockets...
2020-07-19T07:35:49.127+0000 I  -        [initandlisten] Stopping further Flow Control ticket acquisitions.
2020-07-19T07:35:49.128+0000 I  CONTROL  [initandlisten] now exiting
2020-07-19T07:35:49.133+0000 I  CONTROL  [initandlisten] shutting down with code:100
2020-07-19T19:19:54.151+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
```
以下是成功访问的首页截图和jaeger UI的截图：
![%RW%Z}Q{N4Q9MGSLYTN4BN](https://user-images.githubusercontent.com/42533108/87887428-ba9c6a80-ca57-11ea-927b-16679eb679d1.png)
![2A(4)D3GZDIFD$5MN3N}H{W](https://user-images.githubusercontent.com/42533108/87887431-bcfec480-ca57-11ea-9be7-30feb2e5942c.png)

请问这是什么原因呢？

**Comment by zhongyuanzhao000** [comment]
你好，这个问题可能跟您的操作系统、环境变量有关。
这里有一个近似的issue供您参考：#46

**Comment by Butter934** [comment]
还有一个小问题，请问你们这两天更新了codewisdom上的0.0.4版本的镜像吗？我重新拉取镜像再启动为什么jaeger上没有相应的tracing记录了呢？

**Comment by zhongyuanzhao000** [comment]
是的，0.0.4版本的镜像移除了jaeger，是为了降低耦合度，也便于组合使用其他tracing系统。如果要使用jaeger，参考这个部署文件：
https://github.com/FudanSELab/train-ticket/tree/master/deployment/kubernetes-manifests/k8s-with-jaeger
