### ISSUE TITLE
Several MongoDB Connection Failures

### ISSUE THREAD

**Issue by martinstraesser** [FudanSELab/train-ticket#46]
Hello,
I deployed all train-ticket services with the default docker-compose file on a Ubuntu 18.04 LTS server. The application in general starts up correctly and I'm able to access the UI and perform actions. However, when I access the container logs via 
`docker container logs <CONTAINER_NAME>`
I see two kinds of exception in several services.

1. MongoSocketOpenException (Example: admin-user-service)
Relevant Log output:

```
2019-09-28 14:56:21.439  INFO [ts-admin-user-service,,,] 1 --- [localhost:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:27017

com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.SocketStream.open(SocketStream.java:63) ~[mongodb-driver-core-3.4.2.jar!/:na]
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115) ~[mongodb-driver-core-3.4.2.jar!/:na]
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:113) ~[mongodb-driver-core-3.4.2.jar!/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_111]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_111]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_111]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_111]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_111]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_111]
	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:57) ~[mongodb-driver-core-3.4.2.jar!/:na]
	at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[mongodb-driver-core-3.4.2.jar!/:na]
	... 3 common frames omitted
```

This might be related to the issue that docker containers have problems with connecting to localhost. However, any idea how to overcome this? Or a possibility to set address for MongoDB? The error repeats some times and then I get a notification for successful Tomcat startup:

`2019-09-28 14:57:29.794  INFO [ts-admin-user-service,,,] 1 --- [           main] adminuser.AdminUserApplication           : Started AdminUserApplication in 172.133 seconds (JVM running for 183.587)`

2. MongoSocketException (Example: consign-service)
Relevant Log Output:

```
2019-09-28 14:54:40.335  INFO [ts-consign-service,,,] 1 --- [ign-mongo:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server ts-consign-mongo:27017

com.mongodb.MongoSocketException: ts-consign-mongo: Name or service not known
	at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:188) ~[mongodb-driver-core-3.4.2.jar!/:na]
	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:57) ~[mongodb-driver-core-3.4.2.jar!/:na]
	at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[mongodb-driver-core-3.4.2.jar!/:na]
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115) ~[mongodb-driver-core-3.4.2.jar!/:na]
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:113) ~[mongodb-driver-core-3.4.2.jar!/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: java.net.UnknownHostException: ts-consign-mongo: Name or service not known
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_111]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[na:1.8.0_111]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na:1.8.0_111]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[na:1.8.0_111]
	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[na:1.8.0_111]
	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[na:1.8.0_111]
	at java.net.InetAddress.getByName(InetAddress.java:1076) ~[na:1.8.0_111]
	at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:186) ~[mongodb-driver-core-3.4.2.jar!/:na]
	... 5 common frames omitted

2019-09-28 14:54:40.882  INFO [ts-consign-service,,,] 1 --- [ign-mongo:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server ts-consign-mongo:27017

com.mongodb.MongoSocketException: ts-consign-mongo
	at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:188) ~[mongodb-driver-core-3.4.2.jar!/:na]
	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:57) ~[mongodb-driver-core-3.4.2.jar!/:na]
	at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[mongodb-driver-core-3.4.2.jar!/:na]
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115) ~[mongodb-driver-core-3.4.2.jar!/:na]
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:113) ~[mongodb-driver-core-3.4.2.jar!/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: java.net.UnknownHostException: ts-consign-mongo
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280) ~[na:1.8.0_111]
	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[na:1.8.0_111]
	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[na:1.8.0_111]
	at java.net.InetAddress.getByName(InetAddress.java:1076) ~[na:1.8.0_111]
	at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:186) ~[mongodb-driver-core-3.4.2.jar!/:na]
	... 5 common frames omitted
```

In contrast to the first error, this error repeats many times and no correct startup is reported.

I am thankful for any help or advices!

**Comment by zhongyuanzhao000** [comment]
Hello, we deployed all train-ticket services with  docker-compose file on a CentOS server,but it seems to be normal.
Maybe you can check whether there is a environmental configuration problem.
