### ISSUE TITLE
cannot pass compile

### ISSUE THREAD

**Issue by gangz** [FudanSELab/train-ticket#9]
when I compile via mvn -Dmaven.test.skip=true clean package,
the following errors were reported:
[ERROR] Failed to execute goal on project ts-login-service: Could not resolve dependencies for project fdse.microservice:ts-login-service:jar:1.0: The following artifacts could not be resolved: myproject.microservices:micro-service-monitoring-core:jar:1.2.2.BUILD-SNAPSHOT, myproject.microservices:micro-service-monitoring-zipkin:jar:1.2.2.BUILD-SNAPSHOT: Could not find artifact myproject.microservices:micro-service-monitoring-core:jar:1.2.2.BUILD-SNAPSHOT -> [Help 1]

It shows that the artifact micro-service-monitoring-core is not exists.

check the pom.xml

the micro-service-monitoring-core appears in dependency, but not in modules.

**Comment by jichaofdu** [comment]
Sorry, I forgot to attach the additional lib into the repo.
I add an directory named _lib_ in _Document_, that may be helpful.
Thanks!

**Comment by linjinjin123** [comment]
@jichaofdu 
After moving the myproject in my .23 directory, I re-run the comman "mvn clean package -e" and get the following error:
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.006 s
[INFO] Finished at: 2018-07-10T12:06:15+08:00
[INFO] Final Memory: 58M/1216M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ts-login-service: Could not resolve dependencies for project fdse.microservice:ts-login-service:jar:1.0: Failed to collect dependencies at myproject.microservices:micro-service-monitoring-core:jar:1.2.2.BUILD-SNAPSHOT: Failed to read artifact descriptor for myproject.microservices:micro-service-monitoring-core:jar:1.2.2.BUILD-SNAPSHOT: Could not find artifact org.springframework.cloud:spring-cloud-sleuth:pom:1.2.2.BUILD-SNAPSHOT -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project ts-login-service: Could not resolve dependencies for project fdse.microservice:ts-login-service:jar:1.0: Failed to collect dependencies at myproject.microservices:micro-service-monitoring-core:jar:1.2.2.BUILD-SNAPSHOT
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project fdse.microservice:ts-login-service:jar:1.0: Failed to collect dependencies at myproject.microservices:micro-service-monitoring-core:jar:1.2.2.BUILD-SNAPSHOT
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:180)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
        ... 23 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at myproject.microservices:micro-service-monitoring-core:jar:1.2.2.BUILD-SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:172)
        ... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for myproject.microservices:micro-service-monitoring-core:jar:1.2.2.BUILD-SNAPSHOT
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:329)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:535)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:519)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:409)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
        ... 26 more
Caused by: org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact org.springframework.cloud:spring-cloud-sleuth:pom:1.2.2.BUILD-SNAPSHOT
        at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:177)
        at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:226)
        at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1000)
        at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:800)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:329)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:320)
        ... 33 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.springframework.cloud:spring-cloud-sleuth:pom:1.2.2.BUILD-SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
        at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:173)
        ... 38 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.springframework.cloud:spring-cloud-sleuth:pom:1.2.2.BUILD-SNAPSHOT
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:434)
        ... 41 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ts-login-service

**Comment by donydex** [comment]
I have the same problem,had this been solved?

**Comment by linjinjin123** [comment]
> I have the same problem,had this been solved?

No, I have given up. : )
